spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: qny47bsq
  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: localhost
server:
  port: 8080
user:
  url: "http://localhost:8081"